### ISSUE TITLE
How use WModalShowToastView in function component

### ISSUE THREAD

**Issue by lionchi** [mochixuan/react-native-smart-tip#26]
Is it possible to use WModalShowToastView in functional components? If so, how to do this and preferably with an example.

**Comment by mochixuan** [comment]
you can watch this: https://github.com/mochixuan/react-native-smart-tip/blob/master/Example/src/pages/ModalShowToastPage.js

**Comment by lionchi** [comment]
@mochixuan This is an example for a class component. And I need an example for a functional component. And from your class component, it's not clear where this.toastInstance is declared

**Comment by mochixuan** [comment]
```

function Test() {
    const toastInstance = useRef(null);
    function getToastInstance(instance){
        toastInstance.current = instance;
    }

    return (
        <Modal>
            ....
            <ModalShowToastView toastInstance={this.getToastInstance}/>
        </Modal>
    )
}

```

**Comment by lionchi** [comment]
More correct WModalShowToastView or ModalShowToastView?  I have an error like this plan "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components)"  but got: undefined. You likely forgot to export your component from the file it's defined in, or you migth have mixed up default and named imports

**Comment by mochixuan** [comment]
WModalShowToastView

**Comment by lionchi** [comment]
Updated but the error appears the same

**Comment by mochixuan** [comment]
It is runnable, I tested it on the latest package

**Comment by jfhidakatsu** [comment]
I have the same error.

**Comment by zhushenwudi** [comment]
@mochixuan
i copy ModalShowToastPage.js to my project and have the same error. 
annotation "ModalShowToastView toastInstance={this.getToastInstance} " is running, otherwise is error, like:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components)" but got: undefined. You likely forgot to export your component from the file it's defined in, or you migth have mixed up default and named imports.

**Comment by mochixuan** [comment]
import { WModalShowToastView } from 'react-native-smart-tip'
